name: vmamba
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.4.0
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - argparse==1.4.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - automat==25.4.16
      - buildtools==1.0.6
      - causal-conv1d==1.2.1
      - certifi==2025.1.31
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - constantly==23.10.4
      - contourpy==1.3.1
      - cycler==0.12.1
      - decorator==5.2.1
      - docopt==0.6.2
      - editdistance==0.8.1
      - einops==0.8.0
      - executing==2.2.0
      - filelock==3.17.0
      - flatbuffers==25.2.10
      - fonttools==4.55.8
      - fsspec==2025.2.0
      - ftfy==6.3.1
      - furl==2.1.4
      - fvcore==0.1.5.post20221221
      - gast==0.6.0
      - google-pasta==0.2.0
      - greenlet==3.2.4
      - grpcio==1.70.0
      - h5py==3.13.0
      - huggingface-hub==0.28.1
      - hyperlink==21.0.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - incremental==24.7.2
      - iniconfig==2.0.0
      - iopath==0.1.10
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libclang==18.1.1
      - mamba-ssm==2.1.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mat4py==0.6.0
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.1
      - mmpretrain==1.2.0
      - mmsegmentation==1.2.2
      - model-index==0.1.11
      - modelindex==0.0.2
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.4.2
      - ninja==1.11.1.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.1
      - ordered-set==4.1.0
      - orderedmultidict==1.0.1
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - portalocker==3.1.1
      - prettytable==3.14.0
      - prompt-toolkit==3.0.50
      - protobuf==5.29.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.8
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - redo==3.0.0
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - safetensors==0.5.2
      - scikit-image==0.25.1
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - selective-scan==0.0.2
      - shapely==2.0.7
      - simplejson==3.20.2
      - six==1.17.0
      - sqlalchemy==2.0.44
      - stack-data==0.6.3
      - submitit==1.5.2
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - timm==0.4.12
      - tokenizers==0.21.0
      - torch==2.1.0
      - torchaudio==2.2.0
      - torchvision==0.16.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.48.3
      - triton==2.1.0
      - twisted==25.5.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.21.0
      - zope-interface==8.0.1
prefix: /home/botti/miniconda3/envs/vmamba
